# Generated by Django 2.2.16 on 2021-05-12 08:08

from django.conf import settings
from django.db import migrations, models
import openedx.core.djangoapps.content.course_overviews.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_overviews', '0023_newandinterestingtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text="Allowed extensions: ('.png', '.jpg', '.jpeg', '.gif')", null=True, upload_to=openedx.core.djangoapps.content.course_overviews.models.collection_image_assets_path, validators=[openedx.core.djangoapps.content.course_overviews.models.validate_collection_image])),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('series_id', models.CharField(max_length=45, unique=True, verbose_name='Series ID')),
                ('courses', models.ManyToManyField(to='course_overviews.CourseOverview')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Series',
            },
        ),
    ]
