# Generated by Django 2.2.16 on 2021-06-08 15:19

from django.conf import settings
from django.db import migrations, models
import openedx.core.djangoapps.content.course_overviews.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_overviews', '0024_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text="Allowed extensions: ('.png', '.jpg', '.jpeg', '.gif')", null=True, upload_to=openedx.core.djangoapps.content.course_overviews.models.collection_image_assets_path, validators=[openedx.core.djangoapps.content.course_overviews.models.validate_collection_image])),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('collection_type', models.CharField(choices=[('Role', 'Role'), ('Topic', 'Topic')], max_length=25, verbose_name='Type')),
                ('standalone_videos', models.CharField(blank=True, max_length=250)),
                ('curriculum_id', models.CharField(max_length=45, unique=True, verbose_name='Curriculum ID')),
                ('courses', models.ManyToManyField(blank=True, to='course_overviews.CourseOverview')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=None, to=settings.AUTH_USER_MODEL)),
                ('series', models.ManyToManyField(blank=True, to='course_overviews.Series')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Curricula',
            },
        ),
    ]
