# Generated by Django 2.2.16 on 2021-06-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0025_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='collection_type',
            field=models.CharField(choices=[('role', 'Role'), ('topic', 'Topic')], max_length=25, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='standalone_videos',
            field=models.TextField(blank=True),
        ),
    ]
