# Generated by Django 2.2.16 on 2022-03-24 09:42

from django.db import migrations
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0014_fix_nan_value_for_global_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodule',
            name='module_state_key',
            field=opaque_keys.edx.django.models.UsageKeyField(db_column='module_id', db_index=True, max_length=255),
        ),
    ]
