stages:
    - deploy
    - deploy-stage

deploy-dev:
    stage: deploy
    image: registry-gitlab.raccoongang.com/edx/configuration/configuration-ironwood-rg:latest
    variables:
        ANSIBLE_SSH_KEY: $JENKINS_DEPLOY_KEY
        ANSIBLE_VAULT_KEY: $DEVOPS_VAULT_KEY
    environment:
      name: dev
      url: https://lms-dev-ironwood.raccoongang.com/
    script:
        - ansible-playbook dev.yml
    only:
        - master
    except:
        - tags

deploy-stage:
    stage: deploy-stage
    extends: deploy-dev
    image: registry-gitlab.raccoongang.com/edx/configuration/configuration-ironwood-rg:ironwood-rg-v0-0-2
    script:
      - ansible-playbook stage.yml
    environment:
      name: stage
      url: https://lms-staging-ironwood.raccoongang.com/
    when: manual
    only:
      - /^ironwood-rg-stage-v[0-9]+$/
    except:
      - branches
