---
touch-deploy:
    stage: deploy
    script:
        - apk add curl
        - "curl -X POST -F token=${DEPLOY_REPO_TOKEN_HAWTHORN} -F ref=master ${DEPLOY_REPO_TRIGGER_URL_HAWTHORN}"
    only:
        - hawthorn-rg
