stages:
    - deploy
    - deploy-stage

deploy-dev:
    stage: deploy
    image: registry-gitlab.raccoongang.com/duck-team/projects/ironwood-rg/configuration:ironwood-rg-develop
    variables:
        ANSIBLE_SSH_KEY: $JENKINS_DEPLOY_KEY
        ANSIBLE_VAULT_KEY: $DEVOPS_VAULT_KEY
    environment:
      name: dev
      url: https://lms-dev-ironwood.raccoongang.com/
    script:
        - ansible-playbook dev.yml
    only:
        - master

deploy-stage:
    stage: deploy-stage
    extends: deploy-dev
    script:
      - ansible-playbook stage.yml
    environment:
      name: stage
      url: https://lms-staging-ironwood.raccoongang.com/
    only:
      - tags
    when: manual
