stages:
    - build

variables:
    EDX_THEME_REPO: https://github.com/raccoongang/edx-theme.git
    EDX_THEME_BRANCH: base-hawthorn-stage
    EDX_THEME_NAME: rg-theme

before_script:
    - apk add git
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build-base-image:
    stage: build
    tags:
        - dind
    variables:
        BASE_IMAGE: registry-gitlab.raccoongang.com/edx/edx-platform:$CI_COMMIT_REF_SLUG
    script:
        - git clone --depth 1 $EDX_THEME_REPO -b $EDX_THEME_BRANCH themes/$EDX_THEME_NAME
        - docker build -t $BASE_IMAGE .
        - docker build --build-arg base_image=$BASE_IMAGE -t $BASE_IMAGE-static - < static.Dockerfile
        - docker push $BASE_IMAGE
        - docker push $BASE_IMAGE-static
