stages:
    - deploy

deploy-dev:
    stage: deploy
    image: registry-gitlab.raccoongang.com/devops/configuration:ironwood-rg-develop
    script:
        - ansible-playbook dev.yml
    only:
        - master
