stages:
    - deploy
    - deploy-stage
    - deploy-production

deploy-dev:
    stage: deploy
    image: registry-gitlab.raccoongang.com/edx/configuration:ironwood-rg-develop
    variables:
        ANSIBLE_SSH_KEY: $JENKINS_DEPLOY_KEY
        ANSIBLE_VAULT_KEY: $DEVOPS_VAULT_KEY
    environment:
      name: dev
      url: https://lms-dev-project_name.raccoongang.com/
    script:
        - ansible-playbook dev.yml
    only:
        - master
    except:
        - tags

deploy-stage:
    stage: deploy-stage
    extends: deploy-dev
    image: registry-gitlab.raccoongang.com/edx/configuration:$CONFIGURATION_IMAGE_STAGE
    script:
      - ansible-playbook stage.yml
    environment:
      name: stage
      url: https://lms-stage-project_name.raccoongang.com/
    when: manual
    only:
      - /^project_name_stage_v[0-9]+\.[0-9]+\.[0-9]+$/
    except:
      - branches

deploy-production:
    stage: deploy-production
    extends: deploy-stage
    image: registry-gitlab.raccoongang.com/edx/configuration:$CONFIGURATION_IMAGE_PRODUCTION
    script:
      - ansible-playbook production.yml
    environment:
      name: production
      url: https://lms.project_name.domain.tld/
    only:
      - /^project_name_production_v[0-9]+\.[0-9]+\.[0-9]+$/
