stages:
    - deploy
deploy-dev:
    stage: deploy
    image: registry-gitlab.raccoongang.com/edx/configuration:koa-rg-develop
    variables:
        ANSIBLE_SSH_KEY: $JENKINS_DEPLOY_KEY
        ANSIBLE_VAULT_KEY: $DEVOPS_VAULT_KEY
    environment:
      name: dev
      url: https://lms-koa-dev.raccoongang.com/
    script:
        - ansible-playbook dev.yml
    only:
        - koa-rg
    except:
        - tags
    allow_failure: true
