stages:
    - deploy
    - deploy-vanilla
    - deploy-stage
    - deploy-ne
deploy-dev:
    stage: deploy
    image: registry-gitlab.raccoongang.com/owlox-team/configuration:koa-rg-develop
    variables:
        ANSIBLE_SSH_KEY: $JENKINS_DEPLOY_KEY
        ANSIBLE_VAULT_KEY: $DEVOPS_VAULT_KEY
    environment:
      name: dev
      url: https://lms-koa-dev.raccoongang.com/
    script:
        - ansible-playbook dev.yml
    only:
        - master
    except:
        - tags
    allow_failure: true

deploy-vanilla:
    stage: deploy-vanilla
    variables:
        ANSIBLE_SSH_KEY: $JENKINS_DEPLOY_KEY
        ANSIBLE_VAULT_KEY: $DEVOPS_VAULT_KEY
    image: registry-gitlab.raccoongang.com/owlox-team/configuration:koa-rg-develop
    script:
        - ansible-playbook vanilla.yml
    environment:
        name: vanilla
        url: https://lms-koa-vanilla.raccoongang.com/
    only:
        refs:
            - master
        variables:
            - $ENVIRONMENT_TYPE == "vanilla"

deploy-stage:
    stage: deploy-stage
    variables:
        ANSIBLE_SSH_KEY: $JENKINS_DEPLOY_KEY
        ANSIBLE_VAULT_KEY: $DEVOPS_VAULT_KEY
    image: registry-gitlab.raccoongang.com/owlox-team/configuration:koa-rg-develop
    script:
        - ansible-playbook stage.yml
    environment:
        name: stage
        url: https://lms-koa-stage.raccoongang.com/
    only:
        refs:
            - master
        variables:
            - $ENVIRONMENT_TYPE == "stage"
deploy-ne:
    stage: deploy-ne
    variables:
        ANSIBLE_SSH_KEY: $JENKINS_DEPLOY_KEY
        ANSIBLE_VAULT_KEY: $DEVOPS_VAULT_KEY
    image: registry-gitlab.raccoongang.com/owlox-team/configuration:koa-rg-develop
    script:
        - ansible-playbook ne.yml
    environment:
        name: ne
        url: https://lms-koa-ne.raccoongang.com/
    only:
        refs:
            - master
        variables:
            - $ENVIRONMENT_TYPE == "ne"
