---
all:
    hosts:
        juniper_dev:
            ansible_host: sandbox00.raccoongang.com
            ansible_port: 22851
            ansible_user: raccoon
        juniper_devloc:
            ansible_host: 192.168.88.16
            ansible_port: 22
            ansible_user: raccoon
    children:
        juniper:
            hosts:
                juniper_dev:
                juniper_devloc:
