---
all:
    hosts:
        koa_dev:
            ansible_host: 34.254.94.13
            ansible_port: 22
            ansible_user: ubuntu
    children:
        project_name:
            hosts:
                koa_dev:
