---
all:
    hosts:
        koa_dev:
            ansible_host: 3.236.72.172
            ansible_port: 22
            ansible_user: ubuntu
    children:
        project_name:
            hosts:
                koa_dev:
