---
all:
    hosts:
        spectrum_prod:
            ansible_host: 127.0.0.1
            ansible_user: ubuntu
            ansible_connection: local
    children:
        spectrum:
            hosts:
                spectrum_prod:
