---
all:
    hosts:
        ironwood-rg-stage:
            ansible_host: staging01.raccoongang.com
            ansible_port: 22840
            ansible_user: raccoon
        ironwood-rg-dev:
            ansible_host: staging02.raccoongang.com
            ansible_port: 22871
            ansible_user: raccoon
    children:
        ironwood_rg:
            hosts:
                ironwood-rg-dev:
                ironwood-rg-stage:
