---
all:
    hosts:
        koa_dev:
            ansible_host: 176.34.151.42
            ansible_port: 22
            ansible_user: ubuntu
    children:
        project_name:
            hosts:
                koa_dev:
