---
all:
    hosts:
        alu-hq-dev:
            ansible_host: staging04.raccoongang.com
            ansible_port: 22872
            ansible_user: raccoon
    children:
        alu-hq:
            hosts:
                alu-hq-dev:
