---
all:
    hosts:
        juniper_dev:
            ansible_host: sandbox00.raccoongang.com
            ansible_port: 22851
            ansible_user: raccoon
    children:
        juniper:
            hosts:
                juniper_dev:
