---
all:
    hosts:
        koa_dev:
            ansible_host: 172.31.21.239
            ansible_port: 22
            ansible_user: ubuntu
    children:
        project_name:
            hosts:
                koa_dev:
