---
all:
    hosts:
        koa_dev:
            ansible_host: 52.31.136.24
            ansible_port: 22
            ansible_user: ubuntu
        koa_vanilla:
            ansible_host: 54.72.7.226
            ansible_port: 22
            ansible_user: ubuntu

    children:
        koa:
            hosts:
                koa_dev:
                koa_vanilla:
