---
all:
    hosts:
#        campus_prod:
#          ansible_host: 127.0.0.1
#          ansible_user: ubuntu
#          ansible_connection: local
        campus_prod:
          ansible_user: ubuntu
          ansible_host: 34.248.35.2
          ansible_port: 22
        campus_mongo:
          ansible_user: ubuntu
          ansible_host: 54.74.97.168
          ansible_port: 22
        campus_elasticsearch:
          ansible_user: ubuntu
          ansible_host: 3.250.13.250
          ansible_port: 22

    children:
        campus:
            hosts:
                campus_prod:
                campus_mongo:
                campus_elasticsearch:
