---
all:
    hosts:
        ironwood-rg-dev:
            ansible_host: staging04.raccoongang.com
            ansible_port: 22840
            ansible_user: raccoon
    children:
        ironwood-rg:
            hosts:
                ironwood-rg-dev:
