---
EDXAPP_PLATFORM_NAME: "RG Koa"
EDXAPP_LANG: "en_US.UTF-8"
EDXAPP_LANGUAGE_CODE: "en"
EDXAPP_TIME_ZONE: "Europe/Dublin"

# to enable seamless auth between LMS, CMS, preview, discovery, credentials
# all DNS names must be one level upper of EDXAPP_SESSION_COOKIE_DOMAIN
# EDXAPP_SESSION_COOKIE_DOMAIN: ".project_name.domain.tld"
EDXAPP_SITE_NAME: "lms.project_name.domain.tld"
EDXAPP_CMS_SITE_NAME: "cms.project_name.domain.tld"
EDXAPP_PREVIEW_LMS_BASE: "preview.project_name.domain.tld"
EDXAPP_LMS_SITE_NAME: "{{ EDXAPP_SITE_NAME }}"
EDXAPP_LMS_BASE: "{{ EDXAPP_SITE_NAME }}"
EDXAPP_CMS_BASE: "{{ EDXAPP_CMS_SITE_NAME }}"

COMMON_HOSTNAME: "{{ EDXAPP_SITE_NAME }}"
RG_ADD_HOSTNAME_TO_HOSTS_FILE: true

COMMON_LMS_BASE_URL: "{{ EDXAPP_LMS_BASE_SCHEME }}://{{ EDXAPP_LMS_BASE }}"
EDXAPP_LMS_BASE_SCHEME: "{{ 'https' if nginx_ssl else 'http' }}"
EDXAPP_LMS_ROOT_URL: "{{ EDXAPP_LMS_BASE_SCHEME }}://{{ EDXAPP_LMS_BASE }}"

EDXAPP_SESSION_COOKIE_NAME: "{{ EDXAPP_LMS_SITE_NAME }}_edxapp"
EDXAPP_CSRF_COOKIE_SECURE: true
EDXAPP_SESSION_COOKIE_SECURE: true

EDXAPP_USE_GIT_IDENTITY: True
# TODO unificated repositories structures
edx_ansible_source_repo: "https://gitlab.raccoongang.com/edx/configuration.git"
CONFIGURATION_VERSION: "koa-rg-try-fix-deploy"

EDXAPP_GRADE_STORAGE_TYPE_LOCAL: true
EDXAPP_GRADE_STORAGE_TYPE: ''
EDXAPP_GRADE_STORAGE_CLASS: "django.core.files.storage.FileSystemStorage"
EDXAPP_GRADE_ROOT_PATH: "{{ edxapp_media_dir }}/grades"
EDXAPP_GRADE_STORAGE_KWARGS:
  base_url: "{{ EDXAPP_MEDIA_URL }}/grades"
  location: "{{ edxapp_media_dir }}/grades"

EDXAPP_FEATURES_OVERRIDE:
  AUTOMATIC_VERIFY_STUDENT_IDENTITY_FOR_TESTING: true
  RG_DELETE_RETIRED: "{{ COMMON_ENABLE_ACCOUNT_DELETION }}"
  ENABLE_XBLOCK_VIEW_ENDPOINT: true
  ENABLE_RG_INSTRUCTOR_ANALYTICS: "{{ COMMON_RG_INSTRUCTOR_ANALYTICS_ENABLE }}"
  RG_ANALYTICS_GRADE_CRON_MINUTE: '*/15'
  RG_ANALYTICS_GRADE_CRON_HOUR: '*'
  RG_ANALYTICS_GRADE_CRON_DOM: '*'
  RG_ANALYTICS_GRADE_CRON_DOW: '*'
  RG_ANALYTICS_GRADE_CRON_MONTH: '*'
  # RG gamification
  RG_GAMIFICATION:
    ENABLED: True
    RG_GAMIFICATION_ENDPOINT: "https://gamma-koa-dev.raccoongang.com/"
    KEY: "{{ RG_GAMIFICATION_KEY }}"
    SECRET: "{{ RG_GAMIFICATION_SECRET }}"
    IGNORED_EVENT_TYPES:
      - edx.certificate.created
      - edx.course.student_notes.added
  # RG gamification

EDXAPP_FEATURES: "{{ _EDXAPP_FEATURES | combine(EDXAPP_FEATURES_OVERRIDE, recursive=True) }}"

ELASTICSEARCH_CLUSTERED: False

EDXAPP_LMS_ENV_EXTRA:
  RG_SENTRY_DSN: "{{ COMMON_RG_SENTRY_DSN }}"
  THIRD_PARTY_AUTH_BACKENDS:
    - "social_core.backends.google.GoogleOAuth2"
    - "social_core.backends.linkedin.LinkedinOAuth2"
    - "social_core.backends.facebook.FacebookOAuth2"
    - "social_core.backends.azuread.AzureADOAuth2"
    - "social_core.backends.vk.VKOAuth2"
    - "third_party_auth.saml.SAMLAuthBackend"
    - "third_party_auth.lti.LTIAuthBackend"

EDXAPP_CMS_ENV_EXTRA:
  RG_SENTRY_DSN: "{{ COMMON_RG_SENTRY_DSN }}"

EDXAPP_EXTRA_REQUIREMENTS: "{{ _EDXAPP_EXTRA_REQUIREMENTS + GAMMA_EDXAPP_EXTRA_REQUIREMENTS + RG_IA_EDXAPP_EXTRA_REQUIREMENTS }}"

_EDXAPP_EXTRA_REQUIREMENTS: []

# rg_analytics
# EDXAPP_ADDL_INSTALLED_APPS: ['rg_instructor_analytics', 'rg_instructor_analytics_log_collector']
# analytics_log_watcher_sleep_time: 1200
# analytics_processors_aliases: "enrollment video_views discussion student_step course_activity"
# analytics_processors_sleep_time: 1200
RG_IA_EDXAPP_EXTRA_REQUIREMENTS: []
# RG_IA_EDXAPP_EXTRA_REQUIREMENTS:
#   - name: 'git+git@gitlab.raccoongang.com:rg-developers/instructor-analytics@v2.2.1#egg=rg_instructor_analytics'
#     extra_args: '-e'
#   - name: 'git+git@gitlab.raccoongang.com:rg-developers/instructor-analytics-log-collector@v2.2.1#egg=rg_instructor_analytics_log_collector'
#     extra_args: '-e'

CONFIGURE_JWTS: True
