---

edx_platform_repo: "https://github.com/edx/edx-platform.git"
EDX_PLATFORM_VERSION: "open-release/koa.master"
EDXAPP_SITE_NAME: "lms-koa-vanilla.raccoongang.com"
EDXAPP_CMS_SITE_NAME: "cms-koa-vanilla.raccoongang.com"
EDXAPP_PREVIEW_LMS_BASE: "preview-koa-vanilla.raccoongang.com"

EDXAPP_SESSION_COOKIE_DOMAIN: ".raccoongang.com"

## extra
ECOMMERCE_VERSION: 'open-release/koa.master'
DISCOVERY_VERSION: 'open-release/koa.master'
ANALYTICS_API_VERSION: 'open-release/koa.master'
INSIGHTS_VERSION: 'open-release/koa.master'
NOTIFIER_VERSION: 'open-release/koa.master'
CREDENTIALS_VERSION: 'open-release/koa.master'
SANDBOX_ENABLE_NOTES: True
SANDBOX_ENABLE_BLOCKSTORE: False
FORUM_VERSION: 'open-release/koa.master'
COMMON_CONFIG_NO_LOGGING: False
DEVPI_SERVER_VERSION: '5.4.0'
DEVPI_WEB_VERSION: '3.5.2'
DEVPI_CLIENT_VERSION: '5.1.1'
EDX_NOTES_API_VERSION: 'open-release/koa.master'
CERTS_VERSION: 'open-release/koa.master'
COMMON_RETIREMENT_SERVICE_SETUP: true

EDXAPP_LMS_ENV_EXTRA:
  RG_GAMIFICATION:
    ENABLED: True
    RG_GAMIFICATION_ENDPOINT: "https://gamma-koa-dev.raccoongang.com/"
    KEY: "{{ RG_GAMIFICATION_KEY }}"
    SECRET: "{{ RG_GAMIFICATION_SECRET }}"
    IGNORED_EVENT_TYPES: []
EDXAPP_INSTALL_PRIVATE_REQUIREMENTS: "{{ COMMON_RG_INSTRUCTOR_ANALYTICS_ENABLE }}"
EDXAPP_PRIVATE_REQUIREMENTS:
  - name: 'git+git@gitlab.raccoongang.com:rg-developers/instructor-analytics@v3.0.0-rc.8#egg=rg_instructor_analytics'
    extra_args: '-e'
  - name: 'git+git@gitlab.raccoongang.com:rg-developers/instructor-analytics-log-collector@v3.0.0-rc.1#egg=rg_instructor_analytics_log_collector'
    extra_args: '-e'
