---
#SANDBOX_ENABLE_ECOMMERCE: true

ECOMMERCE_WORKER_VERSION: open-release/koa.master

ECOMMERCE_REPOS:
  - PROTOCOL: 'ssh'
    DOMAIN: "gitlab.raccoongang.com"
    PATH: 'edx'
    REPO: 'ecommerce.git'
    DESTINATION: "{{ ecommerce_code_dir }}"
    VERSION: "{{ ECOMMERCE_VERSION }}"
    SSH_KEY: "{{ RG_COMMON_GIT_IDENTITY }}"

ECOMMERCE_BROKER_PASSWORD: "{{ EDXAPP_CELERY_PASSWORD }}"
ECOMMERCE_DATABASE_HOST: localhost
ECOMMERCE_DATABASE_NAME: ecommerce
ECOMMERCE_DATABASE_USER: ecomm001
ECOMMERCE_DJANGO_SETTINGS_MODULE: ecommerce.settings.production
ECOMMERCE_BASE: "ecommerce.koa.campus.gov.il"
ECOMMERCE_ECOMMERCE_URL_ROOT: "{{ EDXAPP_LMS_BASE_SCHEME | default('https') }}://{{ ECOMMERCE_BASE }}"
EDXAPP_ECOMMERCE_API_URL: "{{ ECOMMERCE_ECOMMERCE_URL_ROOT }}/api/v2"
EDXAPP_ECOMMERCE_PUBLIC_URL_ROOT: "{{ ECOMMERCE_ECOMMERCE_URL_ROOT }}"

ECOMMERCE_EDX_API_KEY: "{{ EDXAPP_EDX_API_KEY }}"
ECOMMERCE_JWT_ISSUERS:
  - AUDIENCE: '{{ COMMON_JWT_AUDIENCE }}'
    ISSUER: '{{ COMMON_JWT_ISSUER }}'
    SECRET_KEY: '{{ COMMON_JWT_SECRET_KEY }}'
ECOMMERCE_JWT_SECRET_KEYS:
  - "{{ COMMON_JWT_SECRET_KEY }}"
ECOMMERCE_LANGUAGE_CODE: "{{ EDXAPP_LANGUAGE_CODE }}"
ECOMMERCE_LANGUAGE_COOKIE_NAME: "{{ EDXAPP_LANGUAGE_COOKIE }}"
ECOMMERCE_LMS_URL_ROOT: "{{ EDXAPP_LMS_ROOT_URL }}"
ECOMMERCE_LOGOUT_URL: "{{ ECOMMERCE_ECOMMERCE_URL_ROOT }}/logout/"
ECOMMERCE_SUBSITE1_LOGOUT_URL: "{{ ECOMMERCE_SUBSITE1_URL_ROOT }}/logout/"
ECOMMERCE_MEMCACHE:
  - "{{ memcached_host }}:11211"
ECOMMERCE_NGINX_PORT: 18130

#LiqPay sub 1
ecommerce_subsite_service_name: ecommerce-subsite-sso
ECOMMERCE_SUBSITE1_LMS_ROOT_URL: "https://site.koa.campus.gov.il"
ECOMMERCE_SUBSITE1_URL_ROOT: "{{ EDXAPP_LMS_BASE_SCHEME | default('https') }}://{{ ECOMMERCE_SUBSITE1_BASE }}"

ECOMMERCE_SUBSITE1_BASE: "ecommerce-site.koa.campus.gov.il"
ECOMMERCE_SUBSITE1_LIQPAY_CANCEL_CHECKOUT_PATH: "/checkout/cancel-checkout/"
ECOMMERCE_SUBSITE1_LIQPAY_ERROR_PATH: "/checkout/error/"
ECOMMERCE_SUBSITE1_LIQPAY_HOST: "https://www.liqpay.ua/api/"

# PayPal sub 1
ECOMMERCE_SUBSITE1_PAYPAL_MODE: "sandbox"
ECOMMERCE_SUBSITE1_PAYPAL_RECEIPT_URL: "/checkout/receipt/"
ECOMMERCE_SUBSITE1_PAYPAL_CANCEL_URL: "/checkout/cancel-checkout/"
ECOMMERCE_SUBSITE1_PAYPAL_ERROR_URL: "/checkout/error/"
#LiqPay sub 2
ECOMMERCE_LIQPAY_CANCEL_CHECKOUT_PATH: "/checkout/cancel-checkout/"
ECOMMERCE_LIQPAY_ERROR_PATH: "/checkout/error/"
ECOMMERCE_LIQPAY_HOST: "https://www.liqpay.ua/api/"

# PayPal sub 2
ECOMMERCE_PAYPAL_MODE: "sandbox"
ECOMMERCE_RECEIPT_URL: "/checkout/receipt/"
ECOMMERCE_PAYPAL_CANCEL_URL: "/checkout/cancel-checkout/"
ECOMMERCE_PAYPAL_ERROR_URL: "/checkout/error/"

ECOMMERCE_PAYMENT_PROCESSOR_CONFIG:
  sub1:
    liqpay:
      cancel_checkout_path: "{{ ECOMMERCE_SUBSITE1_LIQPAY_CANCEL_CHECKOUT_PATH }}"
      public_key: "{{ ECOMMERCE_SUBSITE1_LIQPAY_PUBLIC_KEY }}"
      private_key: "{{ ECOMMERCE_SUBSITE1_LIQPAY_PRIVATE_KEY }}"
      error_path: "{{ ECOMMERCE_SUBSITE1_LIQPAY_ERROR_PATH }}"
      host: "{{ ECOMMERCE_SUBSITE1_LIQPAY_HOST }}"
    paypal:
      cancel_url: "{{ ECOMMERCE_SUBSITE1_PAYPAL_CANCEL_URL }}"
      client_id: "{{ ECOMMERCE_SUBSITE1_PAYPAL_CLIENT_ID }}"
      client_secret: "{{ ECOMMERCE_SUBSITE1_PAYPAL_CLIENT_SECRET }}"
      error_url: "{{ ECOMMERCE_SUBSITE1_PAYPAL_ERROR_URL }}"
      mode: "{{ ECOMMERCE_SUBSITE1_PAYPAL_MODE }}"
      receipt_url: "{{ ECOMMERCE_SUBSITE1_PAYPAL_RECEIPT_URL }}"

  edx:
    liqpay:
      cancel_checkout_path: "{{ ECOMMERCE_LIQPAY_CANCEL_CHECKOUT_PATH }}"
      public_key: "{{ ECOMMERCE_LIQPAY_PUBLIC_KEY }}"
      private_key: "{{ ECOMMERCE_LIQPAY_PRIVATE_KEY }}"
      error_path: "{{ ECOMMERCE_LIQPAY_ERROR_PATH }}"
      host: "{{ ECOMMERCE_LIQPAY_HOST }}"
    paypal:
      cancel_url: "{{ ECOMMERCE_PAYPAL_CANCEL_URL }}"
      client_id: "{{ ECOMMERCE_PAYPAL_CLIENT_ID }}"
      client_secret: "{{ ECOMMERCE_PAYPAL_CLIENT_SECRET }}"
      error_url: "{{ ECOMMERCE_PAYPAL_ERROR_URL }}"
      mode: "{{ ECOMMERCE_PAYPAL_MODE }}"
      receipt_url: "{{ ECOMMERCE_PAYPAL_RECEIPT_URL }}"
    stripe:
      publishable_key: "{{ ECOMMERCE_STRIPE_PUBLISHABLE_KEY }}"
      secret_key: "{{ ECOMMERCE_STRIPE_SECRET_KEY }}"
      country: "{{ ECOMMERCE_STRIPE_COUNTRY_CODE }}"

ECOMMERCE_PLATFORM_NAME: "{{ EDXAPP_PLATFORM_NAME }}"
ECOMMERCE_SOCIAL_AUTH_REDIRECT_IS_HTTPS: true
ECOMMERCE_SSL_NGINX_PORT: 443
ECOMMERCE_WORKER_BROKER_HOST: "{{ REDIS_BIND_IP }}"
ECOMMERCE_WORKER_BROKER_PASSWORD: "{{ EDXAPP_CELERY_PASSWORD }}"
ECOMMERCE_WORKER_ECOMMERCE_API_ROOT: "{{ ECOMMERCE_ECOMMERCE_URL_ROOT }}"
ECOMMERCE_WORKER_JWT_ISSUER: "{{ COMMON_JWT_AUDIENCE }}"
ECOMMERCE_WORKER_JWT_SECRET_KEY: "{{ COMMON_JWT_SECRET_KEY }}"

ecommerce_post_migrate_commands:
  - command: >
      ./manage.py create_or_update_site
      --site-id 1
      --site-domain {{ ECOMMERCE_BASE }}
      --site-name {{ ECOMMERCE_BASE }}
      --partner-code edx
      --partner-name "OpenEdx LMS"
      --payment-processors=paypal,liqpay,stripe 
      --client-side-payment-processor=stripe
      --lms-url-root {{ EDXAPP_LMS_ROOT_URL }}
      --sso-client-id {{ ECOMMERCE_SOCIAL_AUTH_EDX_OAUTH2_KEY }}
      --sso-client-secret {{ ECOMMERCE_SOCIAL_AUTH_EDX_OAUTH2_SECRET }}
      --from-email {{ EDXAPP_DEFAULT_FROM_EMAIL }}
      --backend-service-client-id {{ ECOMMERCE_BACKEND_SERVICE_EDX_OAUTH2_KEY }}
      --backend-service-client-secret {{ ECOMMERCE_BACKEND_SERVICE_EDX_OAUTH2_SECRET }}
      --payment-support-email {{ EDXAPP_PAYMENT_SUPPORT_EMAIL }}
      --discovery_api_url https://{{ EDXAPP_DISCOVERY_API_URL }}
    when: True
  - command: >
      ./manage.py waffle_switch payment_processor_active_stripe on
      --create
    when: True
  - command: >
      ./manage.py waffle_flag enable_client_side_checkout
      --everyone
      --staff
      --superusers 
      --authenticated 
      --create
    when: True
  - command: >
      ./manage.py create_or_update_site
      --site-id 2
      --site-domain {{ ECOMMERCE_SUBSITE1_BASE }}
      --site-name {{ ECOMMERCE_SUBSITE1_BASE }}
      --partner-code sub1
      --partner-name "OpenEdx LMS Sub1"
      --payment-processors=paypal,liqpay
      --lms-url-root {{ ECOMMERCE_SUBSITE1_LMS_ROOT_URL }}
      --sso-client-id {{ ECOMMERCE_SUBSITE1_SOCIAL_AUTH_EDX_OAUTH2_KEY }}
      --sso-client-secret {{ ECOMMERCE_SUBSITE1_SOCIAL_AUTH_EDX_OAUTH2_SECRET }}
      --from-email {{ EDXAPP_DEFAULT_FROM_EMAIL }}
      --backend-service-client-id {{ ECOMMERCE_SUBSITE1_BACKEND_SERVICE_EDX_OAUTH2_KEY }}
      --backend-service-client-secret {{ ECOMMERCE_SUBSITE1_BACKEND_SERVICE_EDX_OAUTH2_SECRET }}
      --payment-support-email {{ EDXAPP_PAYMENT_SUPPORT_EMAIL }}
      --discovery_api_url https://{{ EDXAPP_DISCOVERY_API_URL }}
    when: True

ECOMMERCE_ENABLE_COMPREHENSIVE_THEMING: True
ECOMMERCE_DEFAULT_SITE_THEME: "theme"
ECOMMERCE_COMPREHENSIVE_THEME_DIRS:
  - "{{ ECOMMERCE_THEME_DIR }}"

ecommerce_git_home: /edx/app/ecommerce
ECOMMERCE_STATIC_ROOT: /edx/var/ecommerce/staticfiles
ECOMMERCE_THEME_DIR: "{{ COMMON_DATA_DIR }}/ecommerce"
ECOMMERCE_THEME_VERSION: 'koa-rg'
ECOMMERCE_THEMES_REPOS:
  - PROTOCOL: 'ssh'
    DOMAIN: "gitlab.raccoongang.com"
    PATH: 'edx'
    REPO: 'ecommerce-theme.git'
    VERSION: "{{ ECOMMERCE_THEME_VERSION }}"
    DESTINATION: "{{ ECOMMERCE_THEME_DIR }}/{{ ECOMMERCE_DEFAULT_SITE_THEME }}"
    SSH_KEY: "{{ RG_COMMON_GIT_IDENTITY }}"
