---
EDXAPP_SITE_NAME: "courses-koaprod.campus.gov.il"
EDXAPP_CMS_SITE_NAME: "studio-koaprod.campus.gov.il"
EDXAPP_PREVIEW_LMS_BASE: "preview-koaprod.campus.gov.il"

EDX_PLATFORM_VERSION: "campus-prod-release-2022-03-28"
edx_platform_repo: "git@gitlab.raccoongang.com:Duck-Team/projects/campus/edx-platform.git"

EDXAPP_SESSION_COOKIE_DOMAIN: ".campus.gov.il"

COMMON_HOSTNAME: "campus"
EDXAPP_GOOGLE_TAG_MANAGER_ID: "GTM-T2HB8R7"

COMMON_DEFAULT_FROM_EMAIL: "CampusIL <no-reply@campus.gov.il>"

SWAPFILE_SIZE: ''
MONGO_BIND_IP: '0.0.0.0'

## extra
ECOMMERCE_VERSION: 'koa-rg'
DISCOVERY_VERSION: 'open-release/koa.master'
ANALYTICS_API_VERSION: 'open-release/koa.master'
INSIGHTS_VERSION: 'rg-release/koa.3-campus-main'
NOTIFIER_VERSION: 'open-release/koa.master'
CREDENTIALS_VERSION: 'koa-rg'
SANDBOX_ENABLE_NOTES: True
SANDBOX_ENABLE_BLOCKSTORE: False
FORUM_VERSION: 'open-release/ironwood.master'
COMMON_CONFIG_NO_LOGGING: False
DEVPI_SERVER_VERSION: '5.4.0'
DEVPI_WEB_VERSION: '3.5.2'
DEVPI_CLIENT_VERSION: '5.1.1'
EDX_NOTES_API_VERSION: 'open-release/koa.master'
CERTS_VERSION: 'open-release/koa.master'
COMMON_RETIREMENT_SERVICE_SETUP: false

EDXAPP_REDIS_HOSTNAME: 'edxapp-koa-redis.iuvune.0001.euw1.cache.amazonaws.com'
EDXAPP_MEMCACHE: [ 'edxapp-memcache.iuvune.cfg.euw1.cache.amazonaws.com:11211' ]

EDXAPP_COMMENTS_SERVICE_URL: "http://openedx-koa-services-asg-1-1396875031.eu-west-1.elb.amazonaws.com:18080"


EDXAPP_FACEBOOK_PIXEL_ID: hwcacnnpfrdpuk8bvavf94s4321rmn
CAMPUS_ANALYTICS_URL: "https://insights-koaprod.campus.gov.il"

SITE_CONFIGURATION_STORAGE:
    - domain: "{{ EDXAPP_SITE_NAME }}"
      values:
          COURSE_CATALOG_API_URL: https://discovery-koaprod.campus.gov.il/api/v1
          ALWAYS_REDIRECT_HOMEPAGE_TO_DASHBOARD_FOR_AUTHENTICATED_USER: false
          CAMPUS_SAML_PROVIDER_SLUG: moe-edu-idm
          CONTACT_MAILING_ADDRESS: Campus@mail.gov.il
          COURSE_ABOUT_VISIBILITY_PERMISSION: see_about_page
          COURSE_CATALOG_VISIBILITY_PERMISSION: see_in_catalog
          COURSE_EMAIL_FROM_ADDR: CampusIL <support@campus.gov.il>
          COURSE_EMAIL_TEMPLATE_NAME: israelx
          COURSE_HOMEPAGE_INVERT_TITLE: true
          COURSE_HOMEPAGE_SHOW_ORG: false
          COURSE_HOMEPAGE_SHOW_SUBTITLE: false
          DAYS_PASSED_TO_ALERT_PROFILE_INCOMPLETION: -1
          DEFAULT_FROM_EMAIL: campus@mse.gov.il
          EDITABLE_SHORT_DESCRIPTION: true
          EMAIL_FROM_ADDRESS: CampusIL <support@campus.gov.il>
          email_from_address: CampusIL <support@campus.gov.il>
          ENABLE_EXTENDED_COURSE_DETAILS: true
          ENABLE_FORUM_NOTIFICATIONS: true
          ENABLE_MKTG_SITE: false
          EXTENDED_PROFILE_FIELDS:
              - first_name
              - last_name
              - city
              - country
          FIELDS_TO_CHECK_PROFILE_COMPLETION:
              - name
              - country
              - level_of_education
              - gender
              - year_of_birth
          HOMEPAGE_OVERLAY_HTML: ""
          platform_name: IL קמפוס
          PLATFORM_NAME: IL קמפוס
          REGISTRATION_EXTRA_FIELDS:
              first_name: hidden
              last_name: hidden
              level_of_education: optional
              gender: optional
              year_of_birth: optional
              mailing_address: hidden
              goals: hidden
              terms_of_service: required
              honor_code: hidden
              city: optional
              country: optional
              allow_marketing_emails: optional-exposed
          REGISTRATION_FIELD_DEFAULTS:
              country: IL
          REGISTRATION_FIELD_ORDER:
              - "email"
              - "name"
              - "first_name"
              - "last_name"
              - "username"
              - "confirm_email"
              - "password"
              - "terms_of_service"
              - "city"
              - "state"
              - "country"
              - "gender"
              - "year_of_birth"
              - "level_of_education"
              - "specialty"
              - "profession"
              - "company"
              - "title"
              - "mailing_address"
              - "goals"
              - "honor_code"
          SHOW_HEADER_LANGUAGE_SELECTOR: true
          STUDENT_PROFILE_DOWNLOAD_FIELDS:
              - id
              - username
              - name
              - email
              - language
              - location
              - year_of_birth
              - gender
              - level_of_education
              - mailing_address
              - goals
              - meta.first-name
              - meta.last-name
              - meta.city
              - meta.country

EDXAPP_SITE_CONFIGURATION: "{{ SITE_CONFIGURATION_STORAGE }}"

EDXAPP_AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
EDXAPP_AWS_QUERYSTRING_AUTH: false
EDXAPP_AWS_S3_CUSTOM_DOMAIN: prod-olivex-uploads.s3.amazonaws.com
EDXAPP_AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
EDXAPP_AWS_STORAGE_BUCKET_NAME: prod-olivex-uploads
EDXAPP_AWS_SES_REGION_ENDPOINT: email.eu-west-1.amazonaws.com
EDXAPP_AWS_SES_REGION_NAME: eu-west-1
EDXAPP_BLOCK_STRUCTURES_SETTINGS:
    COURSE_PUBLISH_TASK_DELAY: 30
    DIRECTORY_PREFIX: courses/
    PRUNING_ACTIVE: true
    STORAGE_CLASS: storages.backends.s3boto.S3BotoStorage
    STORAGE_KWARGS:
        bucket: prod-olivex-edxapp-course-block-structures
    TASK_DEFAULT_RETRY_DELAY: 30
    TASK_MAX_RETRIES: 5
EDXAPP_DEFAULT_FILE_STORAGE: storages.backends.s3boto.S3BotoStorage
EDXAPP_DJFS:
    bucket: prod-olivex-storage
    prefix: prod-olivex/
    type: s3fs
EDXAPP_XBLOCK_FS_STORAGE_BUCKET: prod-olivex-storage
EDXAPP_XBLOCK_FS_STORAGE_PREFIX: prod-olivex/
EDXAPP_IMPORT_EXPORT_BUCKET: prod-olivex-edxapp-import-export
EDXAPP_FILE_UPLOAD_STORAGE_BUCKET_NAME: prod-olivex-uploads
EDXAPP_FILE_UPLOAD_STORAGE_PREFIX: submissions_attachments

EDXAPP_GRADES_DOWNLOAD:
    BUCKET: ''
    ROOT_PATH: ''
    STORAGE_CLASS: storages.backends.s3boto.S3BotoStorage
    STORAGE_KWARGS:
        bucket: prod-olivex-student-grades
        custom_domain: null
        default_acl: private
        gzip: true
        location: prod
        querystring_auth: true
        querystring_expire: 300
    STORAGE_TYPE: ''
EDXAPP_VIDEO_IMAGE_SETTINGS:
    DIRECTORY_PREFIX: video-images/
    STORAGE_KWARGS:
        base_url: /media/
        location: edx/var/edxapp/media/
    VIDEO_IMAGE_MAX_BYTES: 2097152
    VIDEO_IMAGE_MIN_BYTES: 2048
EDXAPP_VIDEO_TRANSCRIPTS_SETTINGS:
    DIRECTORY_PREFIX: video-transcripts/
    STORAGE_KWARGS:
        base_url: /media/
        location: edx/var/edxapp/media/
    VIDEO_TRANSCRIPTS_MAX_BYTES: 3145728
EDXAPP_VIDEO_UPLOAD_PIPELINE:
    BUCKET: edx-videos
    CONCURRENT_UPLOAD_LIMIT: 4
    ROOT_PATH: prod-olivex/unprocessed

EDXAPP_FINANCIAL_REPORTS:
    BUCKET: prod-olivex-financial-reports
    ROOT_PATH: ""
    STORAGE_TYPE: s3

EDXAPP_GRADE_STORAGE_CLASS: 'storages.backends.s3boto.S3BotoStorage'
EDXAPP_GRADE_STORAGE_KWARGS:
    bucket: 'prod-olivex-student-grades'
    custom_domain: null
    location: 'prod'
    querystring_expire: 300
    querystring_auth: true
    gzip: true
    default_acl: "private"

EDXAPP_S3_HOST: "s3.amazonaws.com"

EDXAPP_PROFILE_IMAGE_BACKEND:
    class: storages.backends.s3boto.S3BotoStorage
    options:
        bucket: prod-olivex-profile-images
        custom_domain: prod-olivex-profile-images.s3.amazonaws.com
        headers:
            Cache-Control: max-age-{{ EDXAPP_PROFILE_IMAGE_MAX_AGE }}
EDXAPP_PROFILE_IMAGE_SECRET_KEY: "5WGU|ZyFg{I7eYUU:6]w"


EDXAPP_MONGO_HOSTS: 'prod-mongo-koa-openedx.cluster-ci3ewl3onmj2.eu-west-1.docdb.amazonaws.com'
FORUM_MONGO_HOSTS:
 - "{{ EDXAPP_MONGO_HOSTS }}"
FORUM_MONGO_URL: "mongodb://{{ FORUM_MONGO_USER }}:{{ FORUM_MONGO_PASSWORD }}@{{ EDXAPP_MONGO_HOSTS }}:27017/{{ FORUM_MONGO_DATABASE }}?replicaSet={{ MONGO_REPL_SET }}&readPreference=secondaryPreferred&retryWrites=false"
MONGO_ADMIN_USER: "root"
mongo_admin_password: "{{ MONGO_ADMIN_PASSWORD }}"
EDXAPP_MONGO_USE_SSL: False
MONGO_REPL_SET: "rs0"

FORUM_RUBY_VERSION: "2.4.1"
forum_services:
  - {service: "elasticsearch", host: "{{ FORUM_ELASTICSEARCH_HOST }}", port: "{{ FORUM_ELASTICSEARCH_PORT }}"}

COMMON_OBJECT_STORE_LOG_SYNC_BUCKET: koa-campus-uat-tracking-logs
COMMON_OBJECT_STORE_LOG_SYNC: True
COMMON_OBJECT_STORE_LOG_SYNC_PREFIX: "logs/tracking/"
COMMON_OBJECT_STORE_LOG_SYNC_SCRIPT: "{{ COMMON_BIN_DIR }}/send-logs-to-object-store"
COMMON_OBJECT_STORE_LOG_SYNC_ON_EXIT: "{{ COMMON_BIN_DIR }}/sync-logs-on-exit"

edxlocal_database_users:
  - {
      db: "{{ ECOMMERCE_DATABASE_NAME | default(None) }}",
      user: "{{ ECOMMERCE_DATABASE_USER | default(None) }}",
      pass: "{{ ECOMMERCE_DATABASE_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ INSIGHTS_DATABASE_NAME | default(None) }}",
      user: "{{ INSIGHTS_DATABASE_USER | default(None) }}",
      pass: "{{ INSIGHTS_DATABASE_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ XQUEUE_MYSQL_DB_NAME | default(None) }}",
      user: "{{ XQUEUE_MYSQL_USER | default(None) }}",
      pass: "{{ XQUEUE_MYSQL_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ EDXAPP_MYSQL_DB_NAME | default(None) }}",
      user: "{{ EDXAPP_MYSQL_USER | default(None) }}",
      pass: "{{ EDXAPP_MYSQL_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ EDXAPP_MYSQL_CSMH_DB_NAME | default(None) }}",
      user: "{{ EDXAPP_MYSQL_CSMH_USER | default(None) }}",
      pass: "{{ EDXAPP_MYSQL_CSMH_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ ANALYTICS_PIPELINE_OUTPUT_DATABASE_NAME | default(None) }}",
      user: "{{ ANALYTICS_PIPELINE_DB_USER | default(None) }}",
      pass: "{{ ANALYTICS_PIPELINE_DB_PASS | default(None) }}"
    }
  - {
      db: "{{ ANALYTICS_API_DEFAULT_DB_NAME | default(None) }}",
      user: "{{ ANALYTICS_API_DEFAULT_DB_USER | default(None) }}",
      pass: "{{ ANALYTICS_API_DEFAULT_DB_PASS | default(None) }}"
    }
  - {
      db: "{{ ANALYTICS_API_REPORTS_DB_NAME | default(None) }}",
      user: "{{ ANALYTICS_API_REPORTS_DB_USER | default(None) }}",
      pass: "{{ ANALYTICS_API_REPORTS_DB_PASS | default(None) }}"
    }
  - {
      db: "{{ HIVE_METASTORE_DATABASE_NAME | default(None) }}",
      user: "{{ HIVE_METASTORE_DATABASE_USER | default(None) }}",
      pass: "{{ HIVE_METASTORE_DATABASE_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ BLOCKSTORE_DEFAULT_DB_NAME | default(None) }}",
      user: "{{ BLOCKSTORE_DATABASE_USER | default(None) }}",
      pass: "{{ BLOCKSTORE_DATABASE_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ CREDENTIALS_DEFAULT_DB_NAME | default(None) }}",
      user: "{{ CREDENTIALS_MYSQL_USER | default(None) }}",
      pass: "{{ CREDENTIALS_MYSQL_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ DISCOVERY_DEFAULT_DB_NAME | default(None) }}",
      user: "{{ DISCOVERY_MYSQL_USER | default(None) }}",
      pass: "{{ DISCOVERY_MYSQL_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ VEDA_WEB_FRONTEND_DEFAULT_DB_NAME | default(None) }}",
      user: "{{ VEDA_WEB_FRONTEND_MYSQL_USER | default(None) }}",
      pass: "{{ VEDA_WEB_FRONTEND_MYSQL_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ REGISTRAR_DEFAULT_DB_NAME | default(None) }}",
      user: "{{ REGISTRAR_MYSQL_USER | default(None) }}",
      pass: "{{ REGISTRAR_MYSQL_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ NOTIFIER_DATABASE_NAME | default(None) }}",
      user: "{{ NOTIFIER_DATABASE_USER | default(None) }}",
      pass: "{{ NOTIFIER_DATABASE_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ GAMMA_DB_NAME | default(None) }}",
      user: "{{ GAMMA_DB_USER | default(None) }}",
      pass: "{{ GAMMA_DB_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ ENTERPRISE_CATALOG_DEFAULT_DB_NAME | default(None) }}",
      user: "{{ ENTERPRISE_CATALOG_MYSQL_USER | default(None) }}",
      pass: "{{ ENTERPRISE_CATALOG_MYSQL_PASSWORD | default(None) }}"
    }
