---

edx_platform_repo: "git@gitlab.raccoongang.com:edx/edx-platform.git"
EDX_PLATFORM_VERSION: "koa-rg"
EDXAPP_SITE_NAME: "lms-koa-ne.raccoongang.com"
EDXAPP_CMS_SITE_NAME: "cms-koa-ne.raccoongang.com"
EDXAPP_PREVIEW_LMS_BASE: "preview-koa-ne.raccoongang.com"

EDXAPP_SESSION_COOKIE_DOMAIN: ".raccoongang.com"

## extra
ECOMMERCE_VERSION: 'koa-rg'
DISCOVERY_VERSION: 'open-release/koa.master'
ANALYTICS_API_VERSION: 'open-release/koa.master'
INSIGHTS_VERSION: 'open-release/koa.master'
NOTIFIER_VERSION: 'open-release/koa.master'
CREDENTIALS_VERSION: 'koa-rg'
SANDBOX_ENABLE_NOTES: True
SANDBOX_ENABLE_BLOCKSTORE: False
FORUM_VERSION: 'open-release/koa.master'
COMMON_CONFIG_NO_LOGGING: False
DEVPI_SERVER_VERSION: '5.4.0'
DEVPI_WEB_VERSION: '3.5.2'
DEVPI_CLIENT_VERSION: '5.1.1'
EDX_NOTES_API_VERSION: 'open-release/koa.master'
CERTS_VERSION: 'open-release/koa.master'
COMMON_RETIREMENT_SERVICE_SETUP: true
EDXAPP_X_FRAME_OPTIONS: ALLOW

EDXAPP_FEATURES_OVERRIDE:
  AUTOMATIC_VERIFY_STUDENT_IDENTITY_FOR_TESTING: true
  RG_DELETE_RETIRED: "{{ COMMON_ENABLE_ACCOUNT_DELETION }}"
  ENABLE_XBLOCK_VIEW_ENDPOINT: true
  # RG Analytics
  ENABLE_RG_INSTRUCTOR_ANALYTICS: "{{ COMMON_RG_INSTRUCTOR_ANALYTICS_ENABLE }}"
  # For task grade_collector_stat
  RG_ANALYTICS_GRADE_CRON_MINUTE: '*/15'
  RG_ANALYTICS_GRADE_CRON_HOUR: '*'
  RG_ANALYTICS_GRADE_CRON_DOM: '*'
  RG_ANALYTICS_GRADE_CRON_DOW: '*'
  RG_ANALYTICS_GRADE_CRON_MONTH: '*'
  #  For task collect_demographics
  RG_ANALYTICS_DEMOGRAPHICS_SCHEDULE:
    minute: '*/15'
    hour: '*'
    day_of_month: '*'
    day_of_week: '*'
    month_of_year: '*'
  # RG Analytics
  # RG gamification
  RG_GAMIFICATION:
    ENABLED: False
    RG_GAMIFICATION_ENDPOINT: "https://gamma-koa-ne.raccoongang.com/"
    KEY: "{{ RG_GAMIFICATION_KEY }}"
    SECRET: "{{ RG_GAMIFICATION_SECRET }}"
    IGNORED_EVENT_TYPES:
      - edx.certificate.created
      - edx.course.student_notes.added
  # RG gamification
  SHOW_LANGUAGE_SELECTOR: true

  UNESCO_SITE_THEME: "unesco-juniper-stage"
  UNESCO_SITE_THEME_BRANCH: "unesco-juniper-stage"

  ATHENA_SITE_THEME: "athena-juniper-stage"
  ATHENA_SITE_THEME_BRANCH: "master"

  UWS_JUNIPER_SITE_THEME: "uws-juniper-stage"
  UWS_JUNIPER_SITE_THEME_BRANCH: "uws-juniper-stage"

  EXAM_JUNIPER_SITE_THEME: "exam-juniper-stage"
  EXAM_JUNIPER_SITE_THEME_BRANCH: "exam-juniper-stage"

EDXAPP_FEATURES: "{{ _EDXAPP_FEATURES | combine(EDXAPP_FEATURES_OVERRIDE, recursive=True) }}"

EDXAPP_ADDL_INSTALLED_APPS: ['rg_instructor_analytics', 'rg_instructor_analytics_log_collector']
analytics_log_watcher_sleep_time: 1200
analytics_processors_aliases: "enrollment video_views discussion student_step course_activity"
analytics_processors_sleep_time: 1200
EDXAPP_INSTALL_PRIVATE_REQUIREMENTS: "{{ COMMON_RG_INSTRUCTOR_ANALYTICS_ENABLE }}"
EDXAPP_PRIVATE_REQUIREMENTS:
  - name: 'git+git@gitlab.raccoongang.com:rg-developers/instructor-analytics@v3.0.0-rc.8#egg=rg_instructor_analytics'
    extra_args: '-e'
  - name: 'git+git@gitlab.raccoongang.com:rg-developers/instructor-analytics-log-collector@v3.0.0-rc.1#egg=rg_instructor_analytics_log_collector'
    extra_args: '-e'
  - name: 'edx-gamma-bridge==1.0.0.juniper.1'
    extra_args: '--extra-index-url https://pypi.raccoongang.com'
  - name: 'edx-gamma-dashboard==1.0.0.juniper.1'
    extra_args: '--extra-index-url https://pypi.raccoongang.com'

SITE_CONFIGURATION_STORAGE:
    - domain: "{{ EDXAPP_SITE_NAME }}"
      values:
        COURSE_CATALOG_API_URL: 'https://discovery-koa-ne.raccoongang.com/api/v1'
        email_from_address: 'no-reply@raccoongang.com'
        payment_support_email: 'info@raccoongang.com'

EDXAPP_SITE_CONFIGURATION: "{{ SITE_CONFIGURATION_STORAGE if COMMON_ENABLE_DISCOVERY else [] }}"
