---
CREDENTIALS_NGINX_PORT: 18151
CREDENTIALS_NGINX_REDIRECT: false
CREDENTIALS_NGINX_REDIRECT_PORT: 80
CREDENTIALS_NGINX_REDIRECT_SSL_PORT: 443
CREDENTIALS_SSL_NGINX_PORT: 48150
 
EDXAPP_CREDENTIALS_BASE: "credentials-staging-ironwood.raccoongang.com"
CREDENTIALS_SINGLE_DOMAIN: "yes"
# EDXAPP_CREDENTIALS_BASE_PORT: "{{ CREDENTIALS_NGINX_PORT }}"
EDXAPP_LMS_BASE_SCHEME: "https"
EDXAPP_CREDENTIALS_BASE_SCHEME: "{{ EDXAPP_LMS_BASE_SCHEME }}"
 
CREDENTIALS_HOSTNAME: "{{ EDXAPP_CREDENTIALS_BASE }}"
 
CREDENTIALS_DEFAULT_DB_NAME: 'credentials'
CREDENTIALS_MYSQL_HOST: "{{ mysql_host }}"
 
CREDENTIALS_DATABASES:
  # rw user
  default:
    ENGINE: 'django.db.backends.mysql'
    NAME: "{{ CREDENTIALS_DEFAULT_DB_NAME }}"
    USER: "{{ CREDENTIALS_MYSQL_USER }}"
    PASSWORD: "{{ CREDENTIALS_MYSQL_PASSWORD }}"
    HOST: "{{ CREDENTIALS_MYSQL_HOST }}"
    PORT: '3306'
    ATOMIC_REQUESTS: true
    CONN_MAX_AGE: 60
 
CREDENTIALS_DOMAIN: "{{ EDXAPP_CREDENTIALS_BASE }}"
 
CREDENTIALS_URL_ROOT: "{{ EDXAPP_CREDENTIALS_BASE_SCHEME | default('https') }}://{{ CREDENTIALS_DOMAIN }}"
CREDENTIALS_LOGOUT_URL: "{{ CREDENTIALS_URL_ROOT }}/logout/"
CREDENTIALS_OAUTH_URL_ROOT: "{{ EDXAPP_LMS_ROOT_URL | default('http://127.0.0.1:8000') }}/oauth2"
CREDENTIALS_OIDC_LOGOUT_URL: "{{ EDXAPP_LMS_ROOT_URL | default('http://127.0.0.1:8000') }}/logout"

CREDENTIALS_TIME_ZONE: 'UTC'
CREDENTIALS_LANGUAGE_CODE: 'en_US.UTF-8'

CREDENTIALS_SOCIAL_AUTH_REDIRECT_IS_HTTPS: false
 
CREDENTIALS_PLATFORM_NAME: "{{ EDXAPP_PLATFORM_NAME }}"
 
# Absolute URL used to get organization data from the organizations api in LMS
CREDENTIALS_ORGANIZATIONS_API_URL: "{{ EDXAPP_LMS_ROOT_URL }}/api/organizations/v0/"
CREDENTIALS_ORGANIZATIONS_API_AUDIENCE: "{{ EDXAPP_JWT_AUDIENCE | default('lms-key') }}"
CREDENTIALS_ORGANIZATIONS_API_SECRET_KEY: "{{ EDXAPP_JWT_SECRET_KEY | default('lms-secret') }}"
 
# Absolute URL used to get user data from the user api in LMS
CREDENTIALS_USER_API_URL: "{{ EDXAPP_LMS_ROOT_URL }}/api/user/v1/"
CREDENTIALS_USER_API_JWT_AUDIENCE: "{{ EDXAPP_JWT_AUDIENCE | default('lms-key') }}"
CREDENTIALS_USER_API_JWT_SECRET_KEY: "{{ EDXAPP_JWT_SECRET_KEY | default('lms-secret') }}"
 
CREDENTIALS_MEDIA_ROOT: '/edx/var/credentials/media'
CREDENTIALS_STATIC_ROOT: '/edx/var/credentials/static'
 
CREDENTIALS_CORS_WHITELIST:
  - "{{ EDXAPP_CREDENTIALS_BASE }}"
  - "{{ EDXAPP_PROGRAMS_BASE }}"
  - "{{ EDXAPP_LMS_BASE }}"
  - "{{ EDXAPP_CMS_BASE }}"
  - "{{ EDXAPP_PREVIEW_LMS_BASE }}"
 
CREDENTIALS_VERSION: open-release/ironwood.1
 
NGINX_CREDENTIALS_GUNICORN_HOSTS:
  - 127.0.0.1
 
credentials_gunicorn_host: "127.0.0.1"
credentials_gunicorn_port: 8150
 
EDXAPP_CREDENTIALS_PUBLIC_SERVICE_URL: "{{ CREDENTIALS_URL_ROOT }}"
EDXAPP_CREDENTIALS_INTERNAL_SERVICE_URL: "{{ CREDENTIALS_URL_ROOT }}"
