---
# CREDENTIALS_DOMAIN: "credentials-dev-project_name.raccoongang.com"
CREDENTIALS_DOMAIN: "credentials-koa-dev.raccoongang.com"
CREDENTIALS_LANGUAGE_CODE: "en-gb"
CREDENTIALS_SERVICE_USER: "credentials_worker"
CREDENTIALS_MEDIA_ROOT: "{{ COMMON_BASE_DIR }}/var/credentials/media"
credentials_cronjob_auto:
  - script: |
      #!/usr/bin/env bash
      
      if ! test -x /edx/bin/python.credentials -o -x /edx/bin/python.edxapp ; then
        # for multi-instance installations: do nothing on non edxapp instances
        exit
      fi
      
      SHELL=/bin/bash
      CREDENTIALS_CFG=/edx/etc/credentials.yml
      LOG_FILE=/edx/var/log/update_credentials/edx.log
      mkdir -p `dirname ${LOG_FILE}`
      exec &>> ${LOG_FILE}
      exec 2>&1
      export SHELL
      export CREDENTIALS_CFG
      
      if test -x /edx/bin/python.credentials ; then
        sudo -Eu credentials /edx/app/credentials/venvs/credentials/bin/python /edx/app/credentials/credentials/manage.py copy_catalog --settings=credentials.settings.production
      else
        echo "credentials service not found" >&2
      fi
    name: "credentials copy catalog"
    filename: "update_credentials.sh"
    minute: "*/10"
credentials_git_home: /edx/app/credentials
CREDENTIALS_VERSION: 'koa-rg'
CREDENTIALS_REPOS:
  - PROTOCOL: 'ssh'
    DOMAIN: "gitlab.raccoongang.com"
    PATH: 'edx'
    REPO: 'credentials.git'
    VERSION: "{{ CREDENTIALS_VERSION }}"
    DESTINATION: "{{ credentials_code_dir }}"
    SSH_KEY: "{{ RG_COMMON_GIT_IDENTITY }}"
CREDENTIALS_CUSTOM_THEME_PACKAGE:
  - name: 'git+https://gitlab.raccoongang.com/edx/credentials-themes.git@0.3.1#egg=edx_credentials_themes==0.3.2'
    extra_args: '-e'
CREDENTIALS_THEME_NAME: 'koa-rg'
